/** @type {import('tailwindcss').Config} */
export default {
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "tertiary": "#dcdddb",
                "tertiary-container": "#c0c1bf",
                "surface-bright": "#393939",
                "secondary-container": "#fe2fd8",
                "inverse-primary": "#00696b",
                "on-secondary-container": "#530045",
                "surface-tint": "#22dcdf",
                "outline-variant": "#3b4949",
                "surface-dim": "#131313",
                "secondary-fixed-dim": "#ffade3",
                "on-primary-container": "#00585a",
                "surface-canvas": "#fafaf8",
                "error": "#ffb4ab",
                "inverse-surface": "#e2e2e2",
                "secondary": "#ffade3",
                "secondary-fixed": "#ffd8ee",
                "surface-variant": "#353535",
                "on-error": "#690005",
                "surface-container-low": "#1b1b1b",
                "tertiary-fixed": "#e2e3e1",
                "inverse-on-surface": "#303030",
                "on-secondary-fixed": "#3a0030",
                "outline": "#859493",
                "on-tertiary-fixed-variant": "#454746",
                "primary-fixed-dim": "#22dcdf",
                "on-background": "#e2e2e2",
                "on-surface": "#e2e2e2",
                "primary-fixed": "#54f8fb",
                "surface-container-lowest": "#0e0e0e",
                "tertiary-fixed-dim": "#c6c7c5",
                "on-secondary-fixed-variant": "#860071",
                "surface-container": "#1f1f1f",
                "primary-container": "#0fd6d9",
                "on-tertiary-container": "#4d4f4e",
                "on-error-container": "#ffdad6",
                "surface-container-high": "#2a2a2a",
                "surface-container-highest": "#353535",
                "on-secondary": "#5f004f",
                "on-tertiary-fixed": "#1a1c1b",
                "error-container": "#93000a",
                "background": "#131313",
                "primary": "#4cf3f6",
                "on-primary": "#003738",
                "border-wireframe": "rgba(255, 255, 255, 0.1)",
                "surface-narrative": "#000000",
                "surface-pivot": "#ffffff",
                "on-primary-fixed": "#002020",
                "on-primary-fixed-variant": "#004f51",
                "on-surface-variant": "#bacac9",
                "text-muted": "#9f9f9f",
                "surface": "#131313",
                "on-tertiary": "#2f3130"
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            spacing: {
                "section-py": "96px",
                "base": "4px",
                "canvas-runway": "128px",
                "stack-lg": "32px",
                "gutter-mobile": "24px",
                "gutter-desktop": "64px",
                "stack-sm": "8px",
                "stack-md": "16px"
            },
            fontFamily: {
                "body-sm": ["Open Sans"],
                "code-block": ["JetBrains Mono"],
                "headline-md": ["Open Sans"],
                "body-lg": ["Open Sans"],
                "headline-lg": ["Open Sans"],
                "headline-lg-mobile": ["Open Sans"],
                "mono-label": ["JetBrains Mono"],
                "display-accent": ["EB Garamond"]
            },
            fontSize: {
                "body-sm": ["15px", { lineHeight: "1.5", fontWeight: "400" }],
                "code-block": ["14px", { lineHeight: "1.7", fontWeight: "400" }],
                "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
                "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
                "headline-lg": ["72px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "700" }],
                "headline-lg-mobile": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
                "mono-label": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
                "display-accent": ["80px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }]
            }
        }
    },
    plugins: [],
}
